### PR TITLE
refactor: Code Refactoring and Optimization

### PR DESCRIPTION
**Pull request by dev-xero**
## Changelog
- Moved title display to separate function
- Fixed spelling mistakes
- Extracted display functionality to separate module
- Setup CMake build chain
- Extracted rectangle calculation logic to separate module
- Created utils module for handling program utility functions
- Defined triangle calculation logic in a separate module
- Defined parallelogram calculation logic in a separate module
- Defined trapezium calculation logic in a separate module
- Clean up and refactoring

## Proposed
- Writing unit tests for each calculation
- Further modularizing the shapes and calculation logic

### CODE REVIEW

**Comment by dev-xero** [comment]
That's rectangle down, three more to go. I'll remove the square functions since, they're still just rectangles

**Comment by dev-xero** [comment]
triangle down, two more to go

**Comment by dev-xero** [comment]
Parallelogram down, only the trapezium implementation left now

**Comment by dev-xero** [comment]
Alright! Trapezium down. Looks good to me 👍🏼

**Comment by ricky-ultimate** [comment]
> Alright! Trapezium down. Looks good to me 👍🏼

Same here. Awesome work!

**Comment by dev-xero** [comment]
All done!

**Pull request merged**
